// examples/vue-chat/components/ChatHeader.vue
<template>
  <header
    class="shrink-0 border-b border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 px-6 py-4"
  >
    <h1 class="text-lg font-semibold text-zinc-900 dark:text-zinc-100">OpenUI Vue Chat</h1>
    <p class="text-xs text-zinc-500 dark:text-zinc-400">
      Powered by @openuidev/vue-lang &amp; Vercel AI SDK
    </p>
  </header>
</template>

// examples/svelte-chat/src/routes/ChatHeader.svelte
<script lang="ts">
</script>

<header
	class="shrink-0 border-b border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 px-6 py-4"
>
	<h1 class="text-lg font-semibold text-zinc-900 dark:text-zinc-100">OpenUI Svelte Chat</h1>
	<p class="text-xs text-zinc-500 dark:text-zinc-400">
		Powered by @openuidev/svelte-lang & Vercel AI SDK
	</p>
</header>
