// examples/vue-chat/components/LoadingIndicator.vue
<template>
  <div class="flex gap-3">
    <div
      class="shrink-0 w-7 h-7 rounded-full bg-gradient-to-br from-violet-500 to-indigo-600 flex items-center justify-center"
    >
      <span class="text-[10px] font-bold text-white">AI</span>
    </div>
    <div class="flex items-center gap-1.5 py-2">
      <div class="w-1.5 h-1.5 bg-zinc-400 rounded-full animate-bounce"></div>
      <div
        class="w-1.5 h-1.5 bg-zinc-400 rounded-full animate-bounce [animation-delay:0.15s]"
      ></div>
      <div class="w-1.5 h-1.5 bg-zinc-400 rounded-full animate-bounce [animation-delay:0.3s]"></div>
    </div>
  </div>
</template>

// examples/svelte-chat/src/routes/LoadingIndicator.svelte
<script lang="ts">
</script>

<div class="flex gap-3">
	<div
		class="shrink-0 w-7 h-7 rounded-full bg-gradient-to-br from-violet-500 to-indigo-600 flex items-center justify-center"
	>
		<span class="text-[10px] font-bold text-white">AI</span>
	</div>
	<div class="flex items-center gap-1.5 py-2">
		<div class="w-1.5 h-1.5 bg-zinc-400 rounded-full animate-bounce"></div>
		<div
			class="w-1.5 h-1.5 bg-zinc-400 rounded-full animate-bounce [animation-delay:0.15s]"
		></div>
		<div
			class="w-1.5 h-1.5 bg-zinc-400 rounded-full animate-bounce [animation-delay:0.3s]"
		></div>
	</div>
</div>
