// examples/multi-agent-chat/src/components/assistant-message.tsx
import type { ActionEvent } from "@openuidev/react-lang";
import { BuiltinActionType, Renderer } from "@openuidev/react-lang";
import { openuiChatLibrary } from "@openuidev/react-ui/genui-lib";
import type { UIMessage } from "ai";
import { Bot } from "lucide-react";
import { ToolCallIndicator } from "./tool-call-indicator";

interface AssistantMessageProps {
  message: UIMessage;
  onSend: (text: string) => void;
}

function isToolPart(
  part: UIMessage["parts"][number],
): part is UIMessage["parts"][number] & { toolCallId: string; state: string } {
  return part.type.startsWith("tool-") || part.type === "dynamic-tool";
}

function getToolName(part: UIMessage["parts"][number]): string {
  if (part.type === "dynamic-tool" && "toolName" in part) {
    return (part as { toolName: string }).toolName;
  }
  return part.type.replace(/^tool-/, "");
}

function getOpenUiToolOutput(part: UIMessage["parts"][number]): string | null {
  if (!("output" in part)) return null;
  const output = (part as { output?: unknown }).output;
  if (!output || typeof output !== "object") return null;

  const openuiSpec = (output as { openuiSpec?: unknown }).openuiSpec;
  return typeof openuiSpec === "string" ? openuiSpec : null;
}


function isOpenUiToolOutputStreaming(part: UIMessage["parts"][number]): boolean {
  if (!("output" in part)) return false;
  const output = (part as { output?: unknown }).output;
  if (!output || typeof output !== "object") return false;

  return (output as { complete?: unknown }).complete === false;
}

export function AssistantMessage({ message, onSend }: AssistantMessageProps) {
  const textContent = message.parts
    .filter((p): p is { type: "text"; text: string } => p.type === "text")
    .map((p) => p.text)
    .join("");

  const toolParts = message.parts.filter(isToolPart);

  const handleAction = (event: ActionEvent) => {
    if (event.type === BuiltinActionType.ContinueConversation && event.humanFriendlyMessage) {
      onSend(event.humanFriendlyMessage);
    }
  };

  const isToolDone = (state: string) => state === "output-available";

  return (
    <div className="flex gap-3 max-w-3xl">
      <div className="shrink-0 w-7 h-7 rounded-full bg-gradient-to-br from-violet-500 to-indigo-600 flex items-center justify-center">
        <Bot size={14} className="text-white" />
      </div>
      <div className="flex-1 min-w-0 space-y-2">
        {toolParts.map((tp) => {
          const toolState = (tp as { state: string }).state;
          const toolName = getToolName(tp);
          const openUiSpec = getOpenUiToolOutput(tp);
          const isOpenUiStreaming = isOpenUiToolOutputStreaming(tp);


          return (
            <div key={(tp as { toolCallId: string }).toolCallId} className="space-y-2">
              <ToolCallIndicator name={toolName} isDone={isToolDone(toolState)} />
              {isToolDone(toolState) && toolName === "analytics_subagent" && openUiSpec && (
                <div className="prose-container">
                  <Renderer
                    response={openUiSpec}
                    library={openuiChatLibrary}
                    isStreaming={isOpenUiStreaming}
                    onAction={handleAction}
                  />
                </div>
              )}
            </div>
          );
        })}
        {textContent && (
          <div className="text-sm leading-6 whitespace-pre-wrap text-zinc-900 dark:text-zinc-100">
            {textContent}
          </div>
        )}
      </div>
    </div>
  );

}

// examples/vue-chat/components/AssistantMessage.vue
<script setup lang="ts">
import { computed } from "vue";
import { Renderer, type ActionEvent, type Library } from "@openuidev/vue-lang";

const props = defineProps<{
  parts: any[];
  library: Library;
  isStreaming: boolean;
  onAction: (event: ActionEvent) => void;
}>();

const textContent = computed(() =>
  props.parts
    .filter((p: any) => p.type === "text")
    .map((p: any) => p.text)
    .join(""),
);

const toolParts = computed(() =>
  props.parts.filter((p: any) => p.type?.startsWith("tool-") || p.type === "dynamic-tool"),
);

function getToolName(part: any): string {
  if (part.type === "dynamic-tool" && "toolName" in part) return part.toolName;
  return part.type?.replace(/^tool-/, "") ?? "";
}
</script>

<template>
  <div class="flex gap-3">
    <div
      class="shrink-0 w-7 h-7 rounded-full bg-gradient-to-br from-violet-500 to-indigo-600 flex items-center justify-center"
    >
      <span class="text-[10px] font-bold text-white">AI</span>
    </div>
    <div class="flex-1 min-w-0 space-y-2">
      <div
        v-for="(tp, i) in toolParts"
        :key="i"
        class="flex items-center gap-2 text-xs text-zinc-500 dark:text-zinc-400"
      >
        <template v-if="(tp as any).state === 'output-available'">
          <svg
            class="w-3.5 h-3.5 text-green-500"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2.5"
              d="M5 13l4 4L19 7"
            />
          </svg>
        </template>
        <template v-else>
          <div
            class="w-3.5 h-3.5 border-2 border-zinc-300 dark:border-zinc-600 border-t-transparent rounded-full animate-spin"
          ></div>
        </template>
        <span class="font-medium">{{ getToolName(tp) }}</span>
      </div>
      <Renderer
        v-if="textContent"
        :response="textContent"
        :library="library"
        :is-streaming="isStreaming"
        :on-action="onAction"
      />
    </div>
  </div>
</template>
